export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/',
  CONJUNTOS: '/conjuntos',
  CONJUNTO_DETAIL: (id: string) => `/conjuntos/${id}`,
  CONJUNTO_NEW: '/conjuntos/nuevo',
  CONJUNTO_EDIT: (id: string) => `/conjuntos/${id}/editar`,
  UNIDADES: '/unidades',
  UNIDAD_DETAIL: (id: string) => `/unidades/${id}`,
  COBRANZA: '/cobranza',
  PQRS: '/pqrs',
  ASAMBLEAS: '/asambleas',
  CONTABILIDAD: '/contabilidad',
  NORMATIVA: '/normativa',
  NOTIFICACIONES: '/notificaciones',
  USUARIOS: '/usuarios',
} as const